// Generated by CoffeeScript 1.6.3
(function() {
  var parseArray;

  window.kidomi = function(data) {
    return parseArray(data);
  };

  parseArray = function(data) {
    if (!data instanceof Array) {
      throw "Expected an array, got: " + data;
    }
  };

}).call(this);

/*
//@ sourceMappingURL=kidomi.map
*/
